format = """
[](mauve)\
$os\
$username\
[](bg:red fg:mauve)\
$directory\
[](fg:red bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:sapphire)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:sapphire bg:teal)\
$docker_context\
[](fg:teal bg:blue)\
$time\
[ ](fg:blue)\
"""

palette = "catppuccin_mocha"

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:mauve"
style_root = "bg:mauve"
format = '[$user ]($style)'
disabled = true

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "fg:text bg:mauve"
disabled = false # Disabled by default

[directory]
style = "bg:red"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:teal"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:peach"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:peach"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:sapphire"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:blue"
format = '[ $time ]($style)'

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
